config/routes.rb
require 'resque/server'

Totablets::Application.routes.draw do

	root to: 'pages#home'

  scope '/admin' do
	  get '/' => 'admins#index', :as => :admin_index
	  resources :key_inputs, :only => [:show, :edit, :update]
	  resources :rentals, :only => [:index, :show]
	  resources :customers, :only => [:index, :show]
	  resources :locations, :except => [:show]
	  resources :notifications, :except => [:show]
	  resources :devices, :except => [:show]
	  resources :taxes, :except => [:show]
	  resources :pre_auths, :only => [:index, :show, :edit, :update]
	  resources :admin_accesses, :only => [:index]
	end

  resources :rentals, :only => [:create]
  post "/location_info" => "rentals#location_info", :as => :location_info
  post "/capture_customer_data" => "rentals#capture_customer_data", :as => :capture_customer_data
  post "/admin_command" => "rentals#admin_command", :as => :admin_command
  post "/install_apps" => "rentals#install_apps", :as => :install_apps

  mount Resque::Server.new, :at => "/resque"

end

app/models/device.rb
class Device < ActiveRecord::Base
	attr_accessible :name, :profile_value, :device_type, :location, :location_id, :admin_password, :demo, :meraki_client_id, :udid

	has_many :rentals
	belongs_to :location

	validates :name, :presence => true
	validates :profile_value, :presence => true
	validates :device_type, :presence => true
	validates :meraki_client_id, :presence => true
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
	http_basic_authenticate_with :name => ENV['ADMIN_NAME'], :password => ENV['ADMIN_PASSWORD']

	def index
		@devices = Device.order("lower(name) ASC")
	end

	def new
		@device = Device.new
	end

	def create
		params[:device][:demo] = params[:device][:demo] == "Demo" ? true : false
		device = Device.new(params[:device])
		if device.save
			flash[:success] = "#{device.name} has been successfully created."
			redirect_to devices_path
		else
			flash.now[:errors] = "Gawd. Fill everything in man."
			@device = device
			render "new"
		end
	end

	def edit
		@device = Device.find(params[:id])
	end

	def update
		device = Device.find(params[:id])
		params[:device][:demo] = params[:device][:demo] == "Demo" ? true : false
		device.assign_attributes(params[:device])
		if device.save
			flash[:success] = "#{device.name} has been updated."
			redirect_to devices_path
		else
			flash.now[:errors] = "Gawd. Fill everything in man."
			@device = device
			render "edit"
		end
	end

	def destroy
		device = Device.find(params[:id]).destroy
		flash[:success] = "#{device.name} has been deleted."
		redirect_to devices_path
	end
end

app/views/devices/_device_form.haml
= form_for @device do |f|
	%fieldset		
		.form-group
			%label{ :for => "device_name" }
				%b Name
			= f.text_field :name, :value => @device.name, :class => "form-control"

		.form-group
			%label{ :for => "device_device_type" }
				%b Device type
			= f.text_field :device_type, :value => @device.device_type, :class => "form-control"

		.form-group
			%label{ :for => "device_location_id" }
				%b Location
			= f.select :location_id, Location.order("lower(name) ASC").collect {|location| [ location.name, location.id ] }, :include_blank => "Dev machine"

		.form-group
			%label{ :for => "device_profile_value" }
				%b Profile value
			= f.text_field :profile_value, :value => @device.profile_value, :class => "form-control"

		.form-group
			%label{ :for => "device_meraki_client_id" }
				%b Meraki client ID
			= f.text_field :meraki_client_id, :value => @device.meraki_client_id, :class => "form-control"

		.form-group
			%label{ :for => "device_udid" }
				%b UDID
			= f.text_field :udid, :value => @device.udid, :class => "form-control"

		.form-group
			%label{ :for => "device_admin_password" }
				%b Admin password
			= f.text_field :admin_password, :value => @device.admin_password, :class => "form-control"

		.form-group
			%label{ :for => "device_demo" }
				%b Type
			= f.select :demo, ["Live", "Demo"], :selected => @device.demo ? 'Demo' : 'Live'

		.submit-button
			%button.btn.btn-success{ :type => "submit" }
				= "#{Device.find_by_id(@device.id) ? "Save" : "Create"}"

			- if Device.find_by_id(@device.id)
				= link_to "Delete", device_path(@device), :method => :delete, :confirm => "You know what you're doing right?  You're about to delete this device...", :style => "margin-left: 10px;"

app/views/devices/edit.haml
.main-container
	.admin-page
		.row
			.span2
				= render "layouts/admin_nav"

			.span8
				#flash
					- flash.each do |name, msg|
						= content_tag :div, msg, :id => "flash_#{name}", class: "alert alert-#{name}"

				%h3 Edit device

				= render "device_form"

app/views/devices/index.haml
.main-container
	.admin-page
		.row
			.span2
				= render "layouts/admin_nav"

			.span8
				#flash
					- flash.each do |name, msg|
						= content_tag :div, msg, :id => "flash_#{name}", class: "alert alert-#{name}"

				%h3.admin-title All devices

				.add-item
					%a{ :href => new_device_path } + Add Device

				%table.table.table-striped
					%tr
						%th Name
						%th Device type
						%th Location
						%th Admin password
						%th Type

					- @devices.each do |device|
						%tr
							%td
								%a{ :href => edit_device_path(device) }
									= device.name
							%td
								= device.device_type
							%td
								= device.location.try(:name) ? device.location.name : "Dev Machine"
							%td
								= device.admin_password
							%td
								= device.demo ? "Demo" : "Live"

app/views/devices/new.haml
.main-container
	.admin-page
		.row
			.span2
				= render "layouts/admin_nav"

			.span8
				#flash
					- flash.each do |name, msg|
						= content_tag :div, msg, :id => "flash_#{name}", class: "alert alert-#{name}"

				%h3 Create device
				
				= render "device_form"