config/routes.rb
require 'resque/server'

Totablets::Application.routes.draw do

	root to: 'pages#home'

  scope '/admin' do
	  get '/' => 'admins#index', :as => :admin_index
	  resources :key_inputs, :only => [:show, :edit, :update]
	  resources :rentals, :only => [:index, :show]
	  resources :customers, :only => [:index, :show]
	  resources :locations, :except => [:show]
	  resources :notifications, :except => [:show]
	  resources :devices, :except => [:show]
	  resources :taxes, :except => [:show]
	  resources :pre_auths, :only => [:index, :show, :edit, :update]
	  resources :admin_accesses, :only => [:index]
	end

  resources :rentals, :only => [:create]
  post "/location_info" => "rentals#location_info", :as => :location_info
  post "/capture_customer_data" => "rentals#capture_customer_data", :as => :capture_customer_data
  post "/admin_command" => "rentals#admin_command", :as => :admin_command
  post "/install_apps" => "rentals#install_apps", :as => :install_apps

  mount Resque::Server.new, :at => "/resque"

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	attr_accessible :name, :email, :stripe_token, :stripe_customer_id

	has_many :rentals
	has_many :location
end

app/models/notification.rb
class Notification < ActiveRecord::Base
	attr_accessible :message, :hours_before_rental_ends, :hour_on_last_day, :location_ids, :url

	has_and_belongs_to_many :locations

	validates :message, :presence => true
	validate :has_only_one_time_column
	validate :legitimate_hours_before_rental_ends
	validate :legitimate_hour_on_last_day

	def has_only_one_time_column
		if hours_before_rental_ends && hour_on_last_day || hours_before_rental_ends.nil? && hour_on_last_day.nil?
			errors.add(:notification_time, "need to have only one time setting")
		end
	end

	def legitimate_hours_before_rental_ends
		if hours_before_rental_ends && hours_before_rental_ends < 0
			errors.add(:hours_before_rental_ends, "need to be greater than 0")
		end
	end

	def legitimate_hour_on_last_day
		if hour_on_last_day && (hour_on_last_day >=24 || hour_on_last_day < 0)
			errors.add(:hour_on_last_day, "need to be less than 24 and greater than 0")
		end
	end

	def display_time_in_words
		if hours_before_rental_ends && hours_before_rental_ends == 99
			return "1 minute after unlock"
		elsif hours_before_rental_ends
			return "#{hours_before_rental_ends} hour#{'s' if hours_before_rental_ends != 1} before rental ends"
		elsif hour_on_last_day
			return "#{hour_on_last_day}:00 on the last day of the rental"
		else
			return "No time specified"
		end
	end

	def message_and_time_in_words
		"#{message} | Displayed: #{display_time_in_words}"
	end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
	http_basic_authenticate_with :name => ENV['ADMIN_NAME'], :password => ENV['ADMIN_PASSWORD']
	
	def index
		@notifications = Notification.all
	end

	def new
		@notification = Notification.new
	end

	def create
		notification = Notification.new(params[:notification])
		if notification.save
			flash[:success] = "Notification ##{notification.id} has been successfully created."
			redirect_to notifications_path
		else
			flash.now[:errors] = "Gawd. Fill everything in correctly man."
			@notification = notification
			render "new"
		end
	end

	def edit
		@notification = Notification.find(params[:id])
	end

	def update
		notification = Notification.find(params[:id])
		notification.assign_attributes(params[:notification])
		if notification.save
			flash[:success] = "Notification ##{notification.id} has been updated."
			redirect_to notifications_path
		else
			flash.now[:errors] = "Gawd. Fill everything in correctly man."
			@notification = notification
			render "edit"
		end
	end

	def destroy
		notification = Notification.find(params[:id]).destroy
		flash[:success] = "Notification ##{notification.id} has been deleted."
		redirect_to notifications_path
	end
end

app/views/notifications/_notification_form.haml
%div{ :style => "margin-bottom: 15px;" }
	%b
		*Note: set only one of either 'hours before rental ends' or 'hour on last day'.  Leave URL blank if not sending the user to a specific URL.  Put 99 as the 'Hours before rental ends' if you want to demo this notification - it will fire 10 seconds after the 60 second countdown.

= form_for @notification do |f|
	%fieldset		
		.form-group
			%label{ :for => "notification_message" }
				%b Message
			= f.text_area :message, :value => @notification.message, :class => "form-control", :style => "width: 400px;", :rows => 5

		.form-group.input-append
			%label{ :for => "notification_hours_before_rental_ends" }
				%b Hours before rental ends
			= f.text_field :hours_before_rental_ends, :value => @notification.hours_before_rental_ends, :class => "form-control input-mini", :style => "text-align:right;"
			%span.add-on hour(s)

		%div
			.form-group.input-append
				%label{ :for => "notification_hour_on_last_day" }
					%b Hour on last day
				= f.text_field :hour_on_last_day, :value => @notification.hour_on_last_day, :class => "form-control input-mini", :style => "text-align:right;"
				%span.add-on :00

		.form-group
			%label{ :for => "notification_url" }
				%b URL
			= f.text_field :url, :value => @notification.url, :class => "form-control"

		%label{ :for => "notification_location_id" }
			%b Location(s)
		.checkbox.inline
			= f.collection_check_boxes :location_ids, Location.all, :id, :name

		.submit-button
			%button.btn.btn-success{ :type => "submit" }
				= "#{Notification.find_by_id(@notification.id) ? "Save" : "Create"}"

			- if Notification.find_by_id(@notification.id)
				= link_to "Delete", notification_path(@notification), :method => :delete, :confirm => "You know what you're doing right?  You're about to delete this notification...", :style => "margin-left: 10px;"

app/views/notifications/edit.haml
.main-container
	.admin-page
		.row
			.span2
				= render "layouts/admin_nav"

			.span8
				#flash
					- flash.each do |name, msg|
						= content_tag :div, msg, :id => "flash_#{name}", class: "alert alert-#{name}"

				%h3 Edit notification

				= render "notification_form"

app/views/notifications/index.haml
.main-container
	.admin-page
		.row
			.span2
				= render "layouts/admin_nav"

			.span8
				#flash
					- flash.each do |name, msg|
						= content_tag :div, msg, :id => "flash_#{name}", class: "alert alert-#{name}"

				%h3.admin-title All notifications

				.add-item
					%a{ :href => new_notification_path } + Add Notification

				%table.table.table-striped
					%tr
						%th ID
						%th Time
						%th Message
						%th Locations

					- @notifications.each do |notification|
						%tr
							%td
								%a{ :href => edit_notification_path(notification) }
									= notification.id
							%td
								= notification.display_time_in_words
							%td
								= notification.message
							%td
								= notification.locations.count == Location.count ? "All" : notification.locations.map{ |location| location.name }.join(", ")

app/views/notifications/new.haml
.main-container
	.admin-page
		.row
			.span2
				= render "layouts/admin_nav"

			.span8
				#flash
					- flash.each do |name, msg|
						= content_tag :div, msg, :id => "flash_#{name}", class: "alert alert-#{name}"

				%h3 Create notification
				
				= render "notification_form"