config/routes.rb
require 'resque/server'

Totablets::Application.routes.draw do

	root to: 'pages#home'

  scope '/admin' do
	  get '/' => 'admins#index', :as => :admin_index
	  resources :key_inputs, :only => [:show, :edit, :update]
	  resources :rentals, :only => [:index, :show]
	  resources :customers, :only => [:index, :show]
	  resources :locations, :except => [:show]
	  resources :notifications, :except => [:show]
	  resources :devices, :except => [:show]
	  resources :taxes, :except => [:show]
	  resources :pre_auths, :only => [:index, :show, :edit, :update]
	  resources :admin_accesses, :only => [:index]
	end

  resources :rentals, :only => [:create]
  post "/location_info" => "rentals#location_info", :as => :location_info
  post "/capture_customer_data" => "rentals#capture_customer_data", :as => :capture_customer_data
  post "/admin_command" => "rentals#admin_command", :as => :admin_command
  post "/install_apps" => "rentals#install_apps", :as => :install_apps

  mount Resque::Server.new, :at => "/resque"

end

app/models/rental.rb
class Rental < ActiveRecord::Base

	attr_accessible :device_name, :location_detail, :days, :start_date, :end_date, :rate, :subtotal, :tax_rate, :tax_amount,
									:grand_total, :currency, :customer, :location, :device, :device_id, :finished, :stripe_rental_charge_id,
									:terms_and_conditions, :demo, :returned

	belongs_to :customer
	belongs_to :location
	belongs_to :device
	has_one :pre_auth
	has_and_belongs_to_many :taxes, :class_name => 'Tax'

	def self.lock_app(device_name)
		device = Device.find_by_name(device_name)

		a = Mechanize.new
		a.get('https://account.meraki.com/secure/login/dashboard_login') do |page|

			my_page = page.form_with(:action => 'https://account.meraki.com/login/login') do |f|
				f.email = ENV['MERAKI_EMAIL']
		    f.password = ENV['MERAKI_PASSWORD']
		  end.click_button

			# Lock device
			a.get("https://n38.meraki.com/Systems-Manager/n/xkWsDaM/manage/configure/pcc_ios") do |settings_page|
			  settings_page.form_with(:action => '/Systems-Manager/n/xkWsDaM/manage/configure/update_pcc_ios') do |form|
			  	form.checkbox_with(:id => "profile_enable_restrictions").check
			  	form["profile[id]"] = device.profile_value
				  form.checkbox_with(:id => "profile_applock_enabled").check
				  form["profile[applock][enabled]"] = true
				  form.field_with(:id => 'profile_applock_app_select').options[4].click
				  form["profile[applock][bundle_identifier]"] = "com.totablets.TOTablets"
				  form.checkbox_with(:id => "profile_proxy_enabled").uncheck
				  after_save_page = form.submit
			  	puts after_save_page.body
				end
			end
		end
	end

	def self.unlock_app(device_name, opts={})
		device = Device.find_by_name(device_name)

		a = Mechanize.new
		a.get('https://account.meraki.com/secure/login/dashboard_login') do |page|

		  my_page = page.form_with(:action => 'https://account.meraki.com/login/login') do |f|
		    f.email = ENV['MERAKI_EMAIL']
		    f.password = ENV['MERAKI_PASSWORD']
		  end.click_button

		  # Unlock device
		  a.get("https://n38.meraki.com/Systems-Manager/n/xkWsDaM/manage/configure/pcc_ios") do |settings_page|
			  settings_page.form_with(:action => '/Systems-Manager/n/xkWsDaM/manage/configure/update_pcc_ios') do |form|
			  	form.checkbox_with(:id => "profile_enable_restrictions").check
			  	form["profile[id]"] = device.profile_value
				  form.checkbox_with(:id => "profile_applock_enabled").uncheck
				  form["profile[applock][enabled]"] = false
			  	form.checkbox_with(:id => "profile_proxy_enabled").uncheck
			  	if opts[:restrict_content] == "yes"
				  	form.checkbox_with(:id => "profile_restrictions_allow_explicit_content").uncheck
				  	form.checkbox_with(:id => "profile_restrictions_allow_safari").uncheck
				  	form["profile[restrictions][rating_movies]"] = "300"
				  	form["profile[restrictions][rating_tv_shows]"] = "500"
				  	form["profile[restrictions][rating_apps]"] = "300"
				  else
				  	form.checkbox_with(:id => "profile_restrictions_allow_explicit_content").check
				  	form.checkbox_with(:id => "profile_restrictions_allow_safari").check
				  	form["profile[restrictions][rating_movies]"] = "1000"
				  	form["profile[restrictions][rating_tv_shows]"] = "1000"
				  	form["profile[restrictions][rating_apps]"] = "1000"
				  end
			  	after_save_page = form.submit
			  	puts after_save_page.body
				end
			end
		end
	end

	def self.manage_single_app_profile(command, device_id, opts)
		device = Device.find(device_id)
		payload = <<-eos
			<DeviceInfo xmlns="http://www.air-watch.com/servicemodel/resources">
			  <Udid>#{device.udid}</Udid>
			</DeviceInfo>
		eos
		# auth = "Basic ZGF2aWRAdG90YWJsZXRzLmNvbTpBc2RmMTIzNA=="
		auth = "Basic ZGF2aWRAdG90YWJsZXRzLmNvbTpXYWhvd2UyMDAh"
		header = { :content_type => :xml, "aw-tenant-code" => "1LSVS4BQAAG5A4TQCFQA", :authorization => auth, :accept => :xml }

		# Order matters when installing / uninstalling apps
		if command == "remove"
	    RestClient.post("https://cn239.awmdm.com/API/v1/mdm/profiles/734/#{command}", payload, header) if Rental.profile_installed?(device, header, 734)
			Rental.manage_apps(device, command, payload, header)
			sleep 1
	    if opts[:restrict_content] == "yes"
	    	# Install adult restriction profile
		    RestClient.post("https://cn239.awmdm.com/API/v1/mdm/profiles/733/install", payload, header) unless Rental.profile_installed?(device, header, 733)
		    # sleep 1
				# Install Mobicip
				# Rental.manage_app("install", 565, payload, header)
			else
				# Install Google Chrome
				Rental.manage_app("install", 564, payload, header)
			end
		else
			Rental.clear_passcode(device, header)
			sleep 1
			Rental.manage_apps(device, command, payload, header)
			RestClient.post("https://cn239.awmdm.com/API/v1/mdm/profiles/734/#{command}", payload, header) unless Rental.profile_installed?(device, header, 734)
			sleep 1
			# Remove adult content profile if it is there
			RestClient.post("https://cn239.awmdm.com/API/v1/mdm/profiles/733/remove", payload, header) if Rental.profile_installed?(device, header, 733)
			sleep 1
			# Remove either Chrome or Mobicip
			Rental.manage_app("uninstall", 564, payload, header) if Rental.app_installed?(device, 564, header)
			# Rental.manage_app("uninstall", 565, payload, header) if Rental.app_installed?(device, 565, header)
		end
	end

	def self.manage_apps(device, command, payload, header)
		apps_requiring_login = [274, 275, 276, 277, 278] # Gmail, Facebook, Twitter, Skype, LinkedIn
		apps_requiring_login.each do |app_id|
			if command == "remove" # If removing single app mode, install apps
				sleep 1
				Rental.manage_app("install", app_id, payload, header) unless Rental.app_installed?(device, app_id, header)
			else # If installing single app mode, delete apps
				Rental.manage_app("uninstall", app_id, payload, header) if Rental.app_installed?(device, app_id, header)
				sleep 1
			end
		end
	end

	def self.manage_app(command, app_id, payload, header)
		RestClient.post("https://cn239.awmdm.com/API/v1/mam/apps/public/#{app_id}/#{command}", payload, header)
	end

	def self.stop_existing_rentals(device)
		ongoing_rentals = device.rentals.select{ |rental| !rental.returned }
		ongoing_rentals.each do |rental|
			rental.update_attributes(:end_date => Time.now, :finished => true, :returned => true)
		end
	end

	def self.clear_passcode(device, header)
		RestClient.post("https://cn239.awmdm.com/API/v1/mdm/devices/udid/#{device.udid}/clearpasscode", {}, header)
	end

	def self.profile_installed?(device, header, profile_id)
		response = RestClient.get("https://cn239.awmdm.com/API/v1/mdm/devices/udid/#{device.udid}/profiles?page=0&pagesize=10", header)
		response_hash = Hash.from_xml response
		response_hash["DeviceProfileSearchResult"]["DeviceProfiles"].each do |profile|
			next unless profile["Id"] == profile_id.to_s
			if profile["Status"] == "confirmedinstall"
				return true
			end
		end
		return false
	end

	def self.app_installed?(device, app_id, header)
		response = RestClient.get("https://cn239.awmdm.com/API/v1/mdm/devices/udid/#{device.udid}/apps?page=0&pagesize=200", header)
		response_hash = Hash.from_xml response
		response_hash["DeviceAppsResult"]["DeviceApps"].each do |profile|
			next unless profile["Id"] == app_id.to_s
			if profile["Status"] == "installed"
				return true
			end
		end
		return false
	end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
	http_basic_authenticate_with :name => ENV['ADMIN_NAME'], :password => ENV['ADMIN_PASSWORD'], :only => [:index, :show]

	def index
		@time_differences = {
			"PST" => 0,
			"MST" => 1,
			"CST" => 2,
			"EST" => 3
		}

		Time.zone = "Pacific Time (US & Canada)"

		if params[:filter].nil? || params[:filter] == "live"
			@rentals = Rental.where(:demo => false).order("start_date DESC").paginate(page: params[:page], :per_page => 25)
		else
			@rentals = Rental.where(:demo => true).order("start_date DESC").paginate(page: params[:page], :per_page => 25)
		end
	end

	def show
		@rental = Rental.find(params[:id])
		time_differences = {
			"PST" => 0,
			"MST" => 1,
			"CST" => 2,
			"EST" => 3
		}
		@hour_differential = time_differences[@rental.location.timezone]

		Time.zone = "Pacific Time (US & Canada)"
	end

	def location_info
		device = Device.find_by_name(params[:ipad_name])
		device = Device.first(:order => "RANDOM()") if device.nil?
		
		if device.demo
			publishable_key = ENV['STRIPE_PUBLISHABLE_KEY']
		else
			publishable_key = ENV['STRIPE_LIVE_PUBLISHABLE_KEY']
		end

		location = device.location
		notifications = {}
		location.notifications.each do |n|
			notifications[n.message] = [n.hours_before_rental_ends, n.hour_on_last_day, n.url]
		end
		taxes = {}
		location.taxes.each { |tax| taxes[tax.name] = tax.rate }
		render :json => {
			"location_name" => "#{location.name}, #{location.city}",
			"currency" => location.currency,
			"rental_fee" => KeyInput.last.rate,
			"pre_auth_amount" => KeyInput.last.pre_auth_amount,
			"publishable_key" => publishable_key,
			"taxes" => taxes,
			"admin_password" => device.admin_password,
			"terms_and_conditions" => KeyInput.last.terms_and_conditions,
			"notifications" => notifications,
			"apple_id_password" => KeyInput.last.apple_id_password,
			"warning" => KeyInput.last.warning
		}
	end

	def create
		device = Device.find_by_name(params["device_name"])
		if device.demo
			Stripe.api_key = ENV['STRIPE_SECRET_KEY']
		else
			Stripe.api_key = ENV['STRIPE_LIVE_SECRET_KEY']
		end

		# Get the credit card details submitted by the form
		token = params[:stripe_token]
		totablets_customer = Customer.find_by_email(params[:email].downcase)

		begin
			pre_auth_amount = params[:pre_auth_amount].to_i

			if totablets_customer
				# Charge a damage / theft pre-authorization on the card
				pre_auth = Stripe::Charge.create(
			    :amount => pre_auth_amount, # in cents
			    :currency => params[:currency].downcase,
			    :customer => totablets_customer.stripe_customer_id,
			    :description => "PRE-AUTHORIZATION: #{params[:location]} iPad rental: #{params[:days]} days at $#{params[:rate].to_i / 100}/day (plus #{params[:tax_names]})",
			    :capture => false
				)

				# Charge the repeat customer instead of the card
				rental_charge = Stripe::Charge.create(
			    :amount => params[:grand_total], # in cents
			    :currency => params[:currency].downcase,
			    :customer => totablets_customer.stripe_customer_id,
			    :description => "#{params[:location]} iPad rental: #{params[:days]} days at $#{params[:rate].to_i / 100}/day (plus #{params[:tax_names]})"
				)
			else
				# Create a Stripe customer
				stripe_customer = Stripe::Customer.create(
				  :card => token,
				  :email => params[:email]
				)

				# Charge a damage / theft pre-authorization on the card
				pre_auth = Stripe::Charge.create(
			    :amount => pre_auth_amount, # in cents
			    :currency => params[:currency].downcase,
			    :customer => stripe_customer.id,
			    :description => "PRE-AUTHORIZATION: #{params[:location]} iPad rental: #{params[:days]} days at $#{params[:rate].to_i / 100}/day (plus #{params[:tax_names]})",
			    :capture => false
				)

				# Charge the new customer instead of the card
				rental_charge = Stripe::Charge.create(
			    :amount => params[:grand_total], # in cents
			    :currency => params[:currency].downcase,
			    :customer => stripe_customer.id,
			    :description => "#{params[:location]} iPad rental: #{params[:days]} days at $#{params[:rate].to_i / 100}/day (plus #{params[:tax_names]})"
				)
			end

		rescue Stripe::CardError => e # Since it's a decline, Stripe::CardError will be caught
		  body = e.json_body
		  err  = body[:error]
		  message = "#{err[:message]} No charge made - please check your credit card information."
		  puts message
		  render :json => { :stripe_error =>  message } and return
		rescue Stripe::InvalidRequestError => e # Invalid parameters were supplied to Stripe's API
		  body = e.json_body
		  err  = body[:error]
		  message = "#{err[:message]} No charge made.  Please notify hotel staff (Params Error)."
		  puts message
		  render :json => { :stripe_error =>  message } and return
		rescue Stripe::AuthenticationError => e # Authentication with Stripe's API failed (maybe you changed API keys recently)
		  body = e.json_body
		  err  = body[:error]
		  message = "#{err[:message]} No charge made.  Please notify hotel staff (API Error)."
		  puts message
		  render :json => { :stripe_error =>  message } and return
		rescue Stripe::APIConnectionError => e # Network communication with Stripe failed
		  body = e.json_body
		  err  = body[:error]
		  message = "#{err[:message]} No charge made.  Please notify hotel staff (Network Error)."
		  puts message
		  render :json => { :stripe_error =>  message } and return
		rescue Stripe::StripeError => e # Display a very generic error to the user, and maybe send yourself an email
		  body = e.json_body
		  err  = body[:error]
		  message = "#{err[:message]} No charge made.  Please notify hotel staff (Generic Error)."
		  puts message
		  render :json => { :stripe_error =>  message } and return
		rescue => e # Something else happened, completely unrelated to Stripe
		  body = e.json_body
		  err  = body[:error]
		  message = "#{err[:message]} No charge made.  Please notify hotel staff (error not related to payment)."
		  puts message
		  render :json => { :stripe_error =>  message } and return
		end

		unless totablets_customer
			totablets_customer = Customer.create(
				:name => params[:name],
				:email => params[:email].downcase,
				:stripe_token => params[:stripe_token],
				:stripe_customer_id => stripe_customer.id
			)
			puts "Created customer: #{totablets_customer.name} - #{totablets_customer.email}"
		end

		opts = {
			:restrict_content => params["restrict_content"]
		}

		Rental.manage_single_app_profile("remove", device.id, opts)

		render :json => {
			:stripe_error => "None", 
			:rental_charge_id => rental_charge.id, 
			:pre_auth_id => pre_auth.id,
			:pre_auth_amount => pre_auth.amount
		}
	end

	def capture_customer_data
		totablets_customer = Customer.find_by_email(params[:email].downcase)

		if totablets_customer
			location = Location.find_by_name(params["location"].split(", ").first)
			device = Device.find_by_name(params["device_name"])
			start_date = DateTime.strptime(params["start_date"].gsub("  0000",""), "%Y-%m-%d %H:%M:%S")
			end_date = DateTime.strptime(params["end_date"].gsub("  0000",""), "%Y-%m-%d %H:%M:%S")

			Rental.stop_existing_rentals(device)

			rental = Rental.create(
	      :location_detail => params["location_detail"],
	      :days => params["days"].to_i,
	      :start_date => start_date,
	      :end_date => end_date,
	      :rate => params["rate"].to_i,
	      :subtotal => params["subtotal"].to_i,
	      :tax_rate => params["tax_percentage"].to_i,
	      :tax_amount => params["tax_amount"].to_i,
	      :grand_total => params["grand_total"].to_i,
				:currency => params["currency"],
				:stripe_rental_charge_id => params["rental_charge_id"],
	      :customer => totablets_customer,
	      :location => location,
				:device => device,
				:terms_and_conditions => params["terms_and_conditions"],
				:demo => device.demo
			)

			PreAuth.create(
				:stripe_pre_auth_id => params["pre_auth_id"],
				:pre_auth_amount => params["pre_auth_amount"].to_i,
				:rental => rental
			)

			params["tax_names"].split(" and ").each do |tax_name|
				tax = Tax.find_by_name(tax_name)
				tax.rentals << rental
			end
			render :json => { :rental => rental.id }
		else
			render :json => { :message => "No customer created yet." }
		end
	end

	def admin_command
		device = Device.find_by_name(params["ipad_name"])
		if params["command"] == "unlock"
			Rental.manage_single_app_profile("remove", device.id, {})
		else
			Rental.stop_existing_rentals(device)
			Rental.manage_single_app_profile("install", device.id, {})
		end
		unless params["origin"] == "finish_rental"
			AdminAccess.create(
				:device_name_during_access => device.name,
				:location_during_access => "#{device.location.name}, #{device.location.city}",
				:action => params["command"]
			)
		end
		render :json => { :command => params["command"] }
	end

	def install_apps
		render :json => { :message => "success" }
	end
end

app/views/rentals/index.haml
.main-container
	.admin-page
		.row
			.span2
				= render "layouts/admin_nav"

			.span8
				#flash
					- flash.each do |name, msg|
						= content_tag :div, msg, :id => "flash_#{name}", class: "alert alert-#{name}"

				%h3.admin-title All rentals

				.filters{:style => "clear:both;"}
					.filter-by{:style => "float:left;"}
						%h4 Filter by:

					.filters{:style => "float:left;margin-top:5px;margin-left:10px;"}
						%ul.nav.nav-pills
							%li{:class => params[:filter] == "live" || params[:filter] == nil || params[:filter].blank? ? "active" : nil}
								%a{:href => "#{rentals_path(:filter => 'live')}"} Live
							%li{:class => params[:filter] == "demo" ? "active" : nil}
								%a{:href => "#{rentals_path(:filter => 'demo')}"} Demo

					.add-item{:style => "line-height:50px;"}
						* = Current rental

				%table.table.table-striped
					%tr
						%th ID
						%th Device
						%th Location
						%th Dates (days)
						%th Total
						%th Status

					- @rentals.each do |rental|
						- if rental.finished && rental.returned
							- status = "Returned"
						- elsif rental.finished && !rental.returned
							- status = "OVERDUE!"
						- else
							- status = "Still out"

						%tr
							%td{ :style => "#{status == 'OVERDUE!' ? 'background-color:yellow;' : ''}" }
								%a{ :href => rental_path(rental) }
									= rental.id
							%td{ :style => "#{status == 'OVERDUE!' ? 'background-color:yellow;' : ''}" }
								%a{ :href => edit_device_path(rental.device) }
									= "#{rental.device.name}#{'*' unless rental.returned}"
							%td{ :style => "#{status == 'OVERDUE!' ? 'background-color:yellow;' : ''}" }
								- if rental.location
									%a{ :href => edit_location_path(rental.location) }
										= "#{rental.location.name}, #{rental.location.city}"
								- else
									Deleted
							%td{ :style => "#{status == 'OVERDUE!' ? 'background-color:yellow;' : ''}" }
								= "#{(rental.start_date + @time_differences[rental.location.timezone].hours).strftime("%b %d")} - #{(rental.end_date + @time_differences[rental.location.timezone].hours).strftime("%b %d")} (#{rental.days})"
							%td{ :style => "#{status == 'OVERDUE!' ? 'background-color:yellow;' : ''}" }
								= "#{number_to_currency(rental.grand_total / 100.0)} #{rental.currency}"
							%td{ :style => "#{status == 'OVERDUE!' ? 'background-color:yellow;' : ''}" }
								= status

				= will_paginate @rentals, :params => { :controller => "rentals", :action => "index" }

app/views/rentals/show.haml
.main-container
	.admin-page
		.row
			.span2
				= render "layouts/admin_nav"

			.span8
				#flash
					- flash.each do |name, msg|
						= content_tag :div, msg, :id => "flash_#{name}", class: "alert alert-#{name}"

				%h3
					= "Rental ID: ##{@rental.id}"

				%table.table.table-striped
					%tr
						- if @rental.finished && @rental.returned
							- status = "Returned"
						- elsif @rental.finished && !@rental.returned
							- status = "OVERDUE!"
						- else
							- status = "Still out"
								
						%td{ :style => "#{status == 'OVERDUE!' ? 'background-color:yellow;' : ''}" }
							%b Status:
						%td{ :style => "#{status == 'OVERDUE!' ? 'background-color:yellow;' : ''}" }
							= status

					%tr
						%td
							%b Customer:
						%td
							%a{ :href => customer_path(@rental.customer) }
								= @rental.customer.name

					%tr
						%td
							%b Device:
						%td
							%a{ :href => edit_device_path(@rental.device) }
								= @rental.device.name

					%tr
						%td
							%b Location:
						%td
							%a{ :href => edit_location_path(@rental.location) }
								= "#{@rental.location.name}, #{@rental.location.city}"

					%tr
						%td
							%b Room number:
						%td
							= @rental.location_detail

					%tr
						%td
							%b Start date and time:
						%td
							= "#{(@rental.start_date + @hour_differential.hours).strftime("%A, %B %d, %Y at %I:%M %p")} #{@rental.location.timezone}"

					%tr
						%td
							%b End date and time:
						%td
							= "#{(@rental.end_date + @hour_differential.hours).strftime("%A, %B %d, %Y at %I:%M %p")} #{@rental.location.timezone}"

					%tr
						%td
							%b Days:
						%td
							= @rental.days

					%tr
						%td
							%b Rate:
						%td
							= "#{number_to_currency(@rental.rate / 100.0)} / day"

					%tr
						%td
							%b Subtotal:
						%td
							= "#{number_to_currency(@rental.subtotal / 100.0)}"

					%tr
						%td
							%b
								= "Tax#{'es' if @rental.taxes.count > 1} applied:"
						%td
							= @rental.taxes.map{ |tax| tax.name }.join(", ")

					%tr
						%td
							%b Total tax rate:
						%td
							= "#{@rental.tax_rate}%"

					%tr
						%td
							%b Tax amount:
						%td
							= "#{number_to_currency(@rental.tax_amount / 100.0)}"

					%tr
						%td
							%b Grand total:
						%td
							= "#{number_to_currency(@rental.grand_total / 100.0)}"

					%tr
						%td
							%b Currency:
						%td
							= @rental.currency

					%tr
						%td
							%b Stripe charge ID:
						%td
							= @rental.stripe_rental_charge_id

					%tr
						%td
							%b Stripe pre-authorization ID:
						%td
							= @rental.pre_auth.stripe_pre_auth_id