config/routes.rb
require 'resque/server'

Totablets::Application.routes.draw do

	root to: 'pages#home'

  scope '/admin' do
	  get '/' => 'admins#index', :as => :admin_index
	  resources :key_inputs, :only => [:show, :edit, :update]
	  resources :rentals, :only => [:index, :show]
	  resources :customers, :only => [:index, :show]
	  resources :locations, :except => [:show]
	  resources :notifications, :except => [:show]
	  resources :devices, :except => [:show]
	  resources :taxes, :except => [:show]
	  resources :pre_auths, :only => [:index, :show, :edit, :update]
	  resources :admin_accesses, :only => [:index]
	end

  resources :rentals, :only => [:create]
  post "/location_info" => "rentals#location_info", :as => :location_info
  post "/capture_customer_data" => "rentals#capture_customer_data", :as => :capture_customer_data
  post "/admin_command" => "rentals#admin_command", :as => :admin_command
  post "/install_apps" => "rentals#install_apps", :as => :install_apps

  mount Resque::Server.new, :at => "/resque"

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	attr_accessible :name, :email, :stripe_token, :stripe_customer_id

	has_many :rentals
	has_many :location
end

app/models/tax.rb
class Tax < ActiveRecord::Base
	attr_accessible :name, :rate, :location_ids

	has_and_belongs_to_many :rentals
	has_and_belongs_to_many :locations

	validates :name, :presence => true
	validates :rate, :presence => true
end

app/controllers/taxes_controller.rb
class TaxesController < ApplicationController
	http_basic_authenticate_with :name => ENV['ADMIN_NAME'], :password => ENV['ADMIN_PASSWORD']

	def index
		@taxes = Tax.order("lower(name) ASC")
	end

	def new
		@tax = Tax.new
	end

	def create
		tax = Tax.new(params[:tax])
		if tax.save
			flash[:success] = "#{tax.name} has been successfully created."
			redirect_to taxes_path
		else
			flash.now[:errors] = "Gawd. Fill everything in man."
			@tax = tax
			render "new"
		end
	end

	def edit
		@tax = Tax.find(params[:id])
	end

	def update
		tax = Tax.find(params[:id])
		tax.assign_attributes(params[:tax])
		if tax.save
			flash[:success] = "#{tax.name} has been updated."
			redirect_to taxes_path
		else
			flash.now[:errors] = "Gawd. Fill everything in man."
			@tax = tax
			render "edit"
		end
	end

	def destroy
		tax = Tax.find(params[:id]).destroy
		flash[:success] = "#{tax.name} has been deleted."
		redirect_to taxes_path
	end
end

app/views/taxes/_tax_form.haml
= form_for @tax do |f|
	%fieldset		
		.form-group
			%label{ :for => "tax_name" }
				%b Name
			= f.text_field :name, :value => @tax.name, :class => "form-control input-mini"

		.form-group.input-append
			%label{ :for => "tax_rate" }
				%b Tax rate
			= f.text_field :rate, :value => @tax.rate, :class => "form-control input-mini", :style => "text-align:right;"
			%span.add-on %

		%label{ :for => "tax_location_id" }
			%b Location(s)
		.checkbox.inline
			= f.collection_check_boxes :location_ids, Location.all, :id, :name

		.submit-button
			%button.btn.btn-success{ :type => "submit" }
				= "#{Tax.find_by_id(@tax.id) ? "Save" : "Create"}"

			- if Tax.find_by_id(@tax.id)
				= link_to "Delete", tax_path(@tax), :method => :delete, :confirm => "You know what you're doing right?  You're about to delete this tax...", :style => "margin-left: 10px;"

app/views/taxes/edit.haml
.main-container
	.admin-page
		.row
			.span2
				= render "layouts/admin_nav"

			.span8
				#flash
					- flash.each do |name, msg|
						= content_tag :div, msg, :id => "flash_#{name}", class: "alert alert-#{name}"

				%h3 Edit tax

				= render "tax_form"

app/views/taxes/index.haml
.main-container
	.admin-page
		.row
			.span2
				= render "layouts/admin_nav"

			.span8
				#flash
					- flash.each do |name, msg|
						= content_tag :div, msg, :id => "flash_#{name}", class: "alert alert-#{name}"

				%h3.admin-title All taxes

				.add-item
					%a{ :href => new_tax_path } + Add tax

				%table.table.table-striped
					%tr
						%th Name
						%th Rate
						%th Locations

					- @taxes.each do |tax|
						%tr
							%td
								%a{ :href => edit_tax_path(tax) }
									= tax.name
							%td
								= "#{tax.rate}%"
							%td
								= tax.locations.map{ |location| location.name }.join(", ")

app/views/taxes/new.haml
.main-container
	.admin-page
		.row
			.span2
				= render "layouts/admin_nav"

			.span8
				#flash
					- flash.each do |name, msg|
						= content_tag :div, msg, :id => "flash_#{name}", class: "alert alert-#{name}"

				%h3 Create tax
				
				= render "tax_form"